import { Footer, Header, Sidebar } from '../components/index';

export const metadata = {
  title: 'ITBANK',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>ITBANK</title>
      </head>
      <body>
        <Header />
        <Sidebar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
