import { Footer, Header, Sidebar } from '../components/index';
import './layout.css';

export const metadata = {
  title: 'ITBANK',
  description: 'Generated by Next.js',
  icons: {
    icon: '/icon.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>ITBANK</title>
      </head>
      <body>
        <Header />
        <div className="container">
          <Sidebar />
          <main className="main">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
